# fly.toml app configuration file generated for simulationauto on 2025-06-30T08:43:58+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simulationauto'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  idle_timeout = "10m"

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
